name: Publish Package to PyPI

on:
  release:
    types: [published]

jobs:
  call-build-wheel:
    uses: ./.github/workflows/build_wheel.yml

  publish-to-pypi:
    name: Publish Package to PyPI
    runs-on: ubuntu-latest
    needs: call-build-wheel

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download wheel artifact
      uses: actions/download-artifact@v5
      with:
        path: dist

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
