name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build-wheel:
    name: "Build wheel ${{ matrix.py_build }} ${{ matrix.arch }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest, windows-11-arm]
        arch: [auto64]
        py_build: ["cp39", "cp310", "cp311", "cp312", "cp313"]
        include:
          - os: ubuntu-24.04-arm
            arch: aarch64
            py_build: "cp39"
          - os: ubuntu-24.04-arm
            arch: aarch64
            py_build: "cp310"
          - os: ubuntu-24.04-arm
            arch: aarch64
            py_build: "cp311"
          - os: ubuntu-24.04-arm
            arch: aarch64
            py_build: "cp312"
          - os: ubuntu-24.04-arm
            arch: aarch64
            py_build: "cp313"

    defaults:
      run:
        shell: ${{ (matrix.os == 'windows-latest' || matrix.os == 'windows-11-arm') && 'msys2 {0}' || 'bash' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install platform-specific requirements (Windows)
      if: runner.os == 'Windows' && runner.arch == 'X64'
      uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64
        path-type: inherit
        install: >-
          mingw-w64-clang-x86_64-autotools
          mingw-w64-clang-x86_64-toolchain

    - name: Install platform-specific requirements (Windows)
      if: runner.os == 'Windows' && runner.arch == 'ARM64'
      uses: msys2/setup-msys2@v2
      with:
        msystem: CLANGARM64
        path-type: inherit
        install: >-
          mingw-w64-clang-aarch64-autotools
          mingw-w64-clang-aarch64-toolchain

    - name: Install platform-specific requirements (macOS)
      if: runner.os == 'macOS'
      run: brew install autoconf automake libtool

    - name: Run cibuildwheel
      run: |
        pip install cibuildwheel delvewheel
        cibuildwheel --output-dir dist
      env:
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_BUILD: "${{ matrix.py_build }}-*"
        CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: delvewheel repair -w {dest_dir} {wheel}

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.py_build }}
        path: dist

  run-tests:
    name: "Test (${{matrix.os}}, Python ${{ matrix.python-version }})"
    runs-on: ${{ matrix.os }}
    needs: build-wheel

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest, windows-11-arm]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        include:
          - python-version: "3.9"
            py_build: "cp39"
          - python-version: "3.10"
            py_build: "cp310"
          - python-version: "3.11"
            py_build: "cp311"
          - python-version: "3.12"
            py_build: "cp312"
          - python-version: "3.13"
            py_build: "cp313"
        exclude:
          - os: windows-11-arm
            python-version: "3.9"
          - os: windows-11-arm
            python-version: "3.10"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Download wheel artifact
      uses: actions/download-artifact@v4
      with:
        name: wheel-${{ matrix.os }}-auto64-${{ matrix.py_build }}

    - name: Download wheels
      run: |
        pip download videotimestamps[dev] -d wheelhouse

    - name: Delete videotimestamps wheel from PyPI
      shell: bash
      run: |
        find wheelhouse -name 'videotimestamps-*.whl' -delete

    - name: Install wheel
      run: |
        pip install videotimestamps[dev] --no-index --find-links . --find-links wheelhouse

    - name: Run tests
      run: |
        pytest

    - name: Typecheck with mypy
      run: |
        mypy

    - name: Check code with ruff
      run: |
        ruff check

    - name: Delete
      shell: bash
      run: |
        rm -rf video_timestamps

    - name: Run coverage
      run: |
        coverage run --source=video_timestamps,tests -m pytest

    - name: Generate coverage report
      run: |
        coverage xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
